"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ONLINE_INTERACTION = exports.ONLINE_MESSAGE_TYPE = exports.SOCKET_EVENT_TYPE = exports.SERVER_EVENT_TYPE = exports.CLIENT_EVENT_TYPE = void 0;
var CLIENT_EVENT_TYPE;
(function (CLIENT_EVENT_TYPE) {
    CLIENT_EVENT_TYPE["JOIN"] = "CL_SEND_JOIN_ROOM";
    CLIENT_EVENT_TYPE["POSITION"] = "CL_SEND_PLAYER_POSITION";
    CLIENT_EVENT_TYPE["ADD"] = "CL_SEND_ADD_OBJECT";
    CLIENT_EVENT_TYPE["REMOVE"] = "CL_SEND_REMOVE_OBJECT";
    CLIENT_EVENT_TYPE["MESSAGE"] = "CL_SEND_MESSAGE";
})(CLIENT_EVENT_TYPE || (exports.CLIENT_EVENT_TYPE = CLIENT_EVENT_TYPE = {}));
var SERVER_EVENT_TYPE;
(function (SERVER_EVENT_TYPE) {
    SERVER_EVENT_TYPE["JOIN"] = "SV_SEND_JOIN_ROOM";
    SERVER_EVENT_TYPE["POSITION"] = "SV_SEND_PLAYER_POSITION";
    SERVER_EVENT_TYPE["ADD"] = "SV_SEND_ADD_OBJECT";
    SERVER_EVENT_TYPE["REMOVE"] = "SV_SEND_REMOVE_OBJECT";
    SERVER_EVENT_TYPE["MESSAGE"] = "SV_SEND_MESSAGES";
    SERVER_EVENT_TYPE["DISCONNECT"] = "SV_SEND_DISCONNECTION";
})(SERVER_EVENT_TYPE || (exports.SERVER_EVENT_TYPE = SERVER_EVENT_TYPE = {}));
var SOCKET_EVENT_TYPE;
(function (SOCKET_EVENT_TYPE) {
    SOCKET_EVENT_TYPE["CONNECTION"] = "connection";
    SOCKET_EVENT_TYPE["DISCONNECT"] = "disconnect";
})(SOCKET_EVENT_TYPE || (exports.SOCKET_EVENT_TYPE = SOCKET_EVENT_TYPE = {}));
var ONLINE_MESSAGE_TYPE;
(function (ONLINE_MESSAGE_TYPE) {
    ONLINE_MESSAGE_TYPE["USER"] = "user";
    ONLINE_MESSAGE_TYPE["CONNECTION"] = "connection";
    ONLINE_MESSAGE_TYPE["DISCONNECTION"] = "disconnection";
})(ONLINE_MESSAGE_TYPE || (exports.ONLINE_MESSAGE_TYPE = ONLINE_MESSAGE_TYPE = {}));
var ONLINE_INTERACTION;
(function (ONLINE_INTERACTION) {
    ONLINE_INTERACTION[ONLINE_INTERACTION["ADD"] = 0] = "ADD";
    ONLINE_INTERACTION[ONLINE_INTERACTION["REMOVE"] = 1] = "REMOVE";
})(ONLINE_INTERACTION || (exports.ONLINE_INTERACTION = ONLINE_INTERACTION = {}));
